# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjWAeL_J81vcFk4N5-_Ntpyz2SFBNcJn
"""



"""
# **WAP to enter a number from user and print its absolute value.**"""

num=int(input("enter the number:"))
print(abs(num))

"""# **WAP to enter a year from user and check if it is leap year or not.**"""

year=int(input("enter the year:"))
if(year%4==0 and year % 100 !=0)or(year%400==0):
  print("leap year")
else:
  print("not a leap year")

"""# **WAP to enter the age of 3 person and print oldest and yougest among them.**"""

age1=int(input("enter the age1:"))
age2=int(input("enter the age2:"))
age3=int(input("enter the age3:"))
if(age1>age2 and age1>age3):
  print("age1 is oldest")
elif(age2>age1 and age2>age3):
  print("age2 is oldest")
else:
  print("age3 is oldest")
  if(age1<age2 and age1<age3):
    print("age1 is youngest")
  elif(age2<age1 and age2<age3):
    print("age2 is youngest")
  else:
    print("age3 is youngest")

"""# **Write a program that asks the user to enter a series of numbers. The program should ask for numbers until the user enters a negative number. Once the user enters a negative number, the program should stop and print the sum of all the positive numbers entered**
# **Example**
# **Enter a number: 5**
# **Enter a number: 8**
# **Enter a number: 12**
# **Enter a number: -2**
# **The sum of the positive numbers is 25.**
"""

num=int(input("enter the number:"))
sum=0
while(num>=0):
  sum=sum+num
  num=int(input("enter the number:"))
print(sum)

"""# **Write a program that asks the user to enter their name and age. The program should check if the user's age is greater than or equal to 18. If it is, the program should print a message saying they are eligible to vote. Otherwise, the program should print a message saying they are not eligible to vote due to being underage.**"""

name=input("enter the name:")
age=int(input("enter the age:"))
if(age>=18):
  print("eligible to vote")
else:
  print("not eligible to vote")

"""# **Write a Python Program to Find the Factorial of a Number**"""

num=int(input("enter the number:"))
for i in range(1,num+1):
  if(num%i==0):
    print(i)